name: ci

on:
  push:
    branches:
      - "master"
      - "stag"

jobs:
  deploy:
    name: Build And Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Production Deploy
        if: github.ref == 'refs/heads/master'
        uses: appleboy/ssh-action@v0.1.2
        env:
          GB_TOKEN: ${{ secrets.GB_TOKEN }}

        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          envs: GB_TOKEN
          script: |
            git clone https://$GB_TOKEN:x-oauth-basic@github.com/overdollc/tali-v2.git
            cd tali-v2
            git checkout master
            git pull origin
            docker-compose up --build --force-recreate -d

      - name: Staging Deploy
        if: github.ref == 'refs/heads/stag'
        uses: appleboy/ssh-action@v0.1.2
        env:
          GB_TOKEN: ${{ secrets.GB_TOKEN }}

        with:
          host: ${{ secrets.SERVER_IP_STAG }}
          username: ${{ secrets.SERVER_USERNAME_STAG }}
          password: ${{ secrets.SERVER_PASSWORD_STAG }}
          envs: GB_TOKEN
          script: |
            git clone https://$GB_TOKEN:x-oauth-basic@github.com/overdollc/tali-v2.git
            cd tali-v2
            git checkout master
            git pull origin
            docker-compose up --build --force-recreate -d
